format_version: 10
pipelines:
  YAML-Pipeline:
    group: GoCD
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-505a42e:
        git: https://github.com/skaparthi1/GoCD.git
        shallow_clone: false
        auto_update: true
        branch: main
    stages:
    - Stage1:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: manual
          allow_only_on_success: false
        jobs:
          Job1:
            timeout: 0
            tasks:
              - task: "Pull file from SFTP"
                command: "lftp"
                arguments:
                  - "-u"
                  - "sftpuser,12345"
                  - "sftp://192.168.56.107"
                options:
                  inline_script: |
                    get /files/*.zip -o /home/ubuntu/prime-square/
                    bye
