format_version: 10
pipelines:
  YAML-Pipeline:
    group: GoCD
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-505a42e:
        git: https://github.com/skaparthi1/GoCD.git
        shallow_clone: false
        auto_update: true
        branch: main
    stages:
    - Stage1:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: manual
          allow_only_on_success: false
        jobs:
          Job1:
            timeout: 0
            tasks:
              - exec:
                  command: lftp
                  arguments:
                    - "-u"
                    - "sftpuser,$SFTP_PASSWORD"  # Use environment variable for the password
                    - "sftp://192.168.56.107"
                    - "-e"
                    - |
                        ls /files/   # List files for debugging
                        get /files/*.zip -o /home/ubuntu/prime-square/
                        bye
    environment_variables:
      SFTP_PASSWORD: "12345"  
